### PR TITLE
opensd: unstable-2022-10-28 -> unstable-2022-12-08

### PR DESCRIPTION
**Pull request by lheckemann**

### CODE REVIEW

**Comment by samueldr** [comment]
- https://gitlab.com/open-sd/opensd/-/compare/e00bc74e516769dbb4adeebde3102657f8a486eb...6c937c9daf20bba17ca97ba5a2332dcce2d4f310#ab09011fa121d0a2bb9fa4ca76094f2482b902b7

**Comment by samueldr** [comment]
I'm guessing you tested the change and either nothing changed, or bug were fixed?

Though as you're probably currently the only user (which is fine), it probably is fine to merge.

**Comment by lheckemann** [comment]
Yep, it worked better (it was complaining about some unexpected events or something.. uhh.. I should probably have documented why I did this)...

**Comment by samueldr** [comment]
Next time :)

**Pull request merged**
