### PR TITLE
sdgyrodsu: unstable-2022-08-22 -> 2.0

### PR DESCRIPTION
**Pull request by K900**
Seems to work, but more testing is appreciated.

### CODE REVIEW

**Comment by misuzu** [comment]
For me it crashes on boot and needs a manual restart:
```
-- Boot cc06752eff5247f1857e6793a733bd61 --
Nov 08 18:35:22 nijika systemd[1409]: Started Cemuhook DSU server for the Steam Deck Gyroscope.
Nov 08 18:35:22 nijika sdgyrodsu[1422]: SteamDeckGyroDSU Version: 2.0
Nov 08 18:35:22 nijika sdgyrodsu[1422]: HidDevReader: Pipeline initialized. Waiting for start...
Nov 08 18:35:22 nijika sdgyrodsu[1422]: CemuhookAdapter: Initialized. Waiting for start of frame grab.
Nov 08 18:35:22 nijika sdgyrodsu[1422]: Server: Initializing.
Nov 08 18:35:22 nijika sdgyrodsu[1422]: terminate called after throwing an instance of 'std::runtime_error'
Nov 08 18:35:22 nijika sdgyrodsu[1422]:   what():  Server: Bind failed.
Nov 08 18:35:22 nijika systemd[1409]: sdgyrodsu.service: Main process exited, code=dumped, status=6/ABRT
Nov 08 18:35:22 nijika systemd[1409]: sdgyrodsu.service: Failed with result 'core-dump'.
Nov 08 18:35:59 nijika systemd[1409]: Started Cemuhook DSU server for the Steam Deck Gyroscope.
Nov 08 18:35:59 nijika sdgyrodsu[2305]: SteamDeckGyroDSU Version: 2.0
Nov 08 18:35:59 nijika sdgyrodsu[2305]: HidDevReader: Pipeline initialized. Waiting for start...
Nov 08 18:35:59 nijika sdgyrodsu[2305]: CemuhookAdapter: Initialized. Waiting for start of frame grab.
Nov 08 18:35:59 nijika sdgyrodsu[2305]: Server: Initializing.
Nov 08 18:35:59 nijika sdgyrodsu[2305]: Server: Socket created at IP: 0.0.0.0 Port: 26760.
Nov 08 18:35:59 nijika sdgyrodsu[2305]: Server: Initialized.
Nov 08 18:35:59 nijika sdgyrodsu[2305]: Server: Start listening for client.
```

**Comment by K900** [comment]
OK, maybe the `After=sockets.target` was actually relevant...

**Comment by K900** [comment]
Should be good now.

**Review by misuzu — APPROVED** [review]
It starts on boot, works with Cemu and Yuzu

**Pull request merged**
