### PR TITLE
linux-jovian: 6.1.52-valve14 -> 6.5.0-valve1

### PR DESCRIPTION
**Pull request by ElvishJerricco**
Marking this as a draft because I don't actually understand the kernel config changes, and I don't know if new configs are needed.

### CODE REVIEW

**Comment by K900** [comment]
The Deck specific config fragments in the PKGBUILDs are identical.

**Comment by ElvishJerricco** [comment]
@K900 So you think these config changes are good as is?

**Comment by K900** [comment]
No, we should really figure out where this stuff went.

**Comment by ElvishJerricco** [comment]
Seems like this tag was not intended to be usable.

**Pull request closed without merging**
