### PR TITLE
steamdeck/sound: change how we make vendor config preferred

### PR DESCRIPTION
**Pull request by K900**
This doesn't actually matter but it costs us nothing and brings us closer to vendor so why not.

### CODE REVIEW

**Comment by pongo1231** [comment]
For whatever reason this makes the "Default" audio profile unavailable on my end and breaks audio output in gamescope-session with Steam forcing the "auto_null" output device. Under KDE I only have "Stereo Input" and "Pro Audio" as profile options now.

**Comment by K900** [comment]
You will probably need to restart the system for this to get picked up correctly.

**Comment by pongo1231** [comment]
Still no bueno even after rebooting unfortunately. Tried also deleting ~/.local/state/wireplumber just in case.

**Comment by K900** [comment]
Sorry, fixed in the latest commit on development.

**Comment by pongo1231** [comment]
Yup works now with cfddf9e15b756c6cb454baca8cf06312023f2db9.

**Pull request merged**
