### PR TITLE
steamdeck: Enable bluetooth

### PR DESCRIPTION
**Pull request by azuwis**

### CODE REVIEW

**Comment by K900** [comment]
That feels overengineered for an option that isn't at all device specific?

**Comment by azuwis** [comment]
How about `modules/steamdeck/bluetooth.nix`:

```
{ config, lib, pkgs, ... }:

{
  hardware.bluetooth.enable = true;
}
```

**Comment by K900** [comment]
I don't know if it's worth it, but maybe? @samueldr's refactor PR might have a better place to put this.

**Comment by ChocolateLoverRaj** [comment]
Steam deck mode has a Bluetooth option in settings. Without Bluetooth enabled by default, people who have Bluetooth capable computers running NixOS with Jovian might be confused about why they can't connect bluetooth devices through Steam deck mode.

**Comment by samueldr** [comment]
(Sorry it took a while to come back to this.)

I think the solution (I'll try opening a PR soon with this) will instead to `mkDefault true` under the `useSteamOSConfig` flag.

It's a Steam OS expectation that isn't upheld by our config.

**Pull request closed without merging**
