### PR TITLE
linux_jovian: 5.13 -> 6.1.12

### PR DESCRIPTION
**Pull request by samueldr**
No comparison link, as we're moving from major to major release.

* * *

It likely will need to pick up the changes for the other misc bits and bobs like the newer UCM files.

* * *

### What was done

 - Booted
 - Tested audio (with #49 applied)
 - Tested steam deck dock
 - jupiter fan control (required a fix)

#### Dock issues

MST plain and simply does not work. Known good setups do not work on 6.1. This includes the Steam Deck dock with either 20221026.01 or 20230126.01 firmware. This also includes my previous *squid-like* setup. Though using a single output from either docks works fine.

(I'll note that with 20230126.01 using a DP to HDMI adapter still does not work with my limited testing.)

These issues are not blocking this PR. This is now assumed to be an unsupported configuration by upstream.

#### DPMS on internal display not working on X11?

Tested with `xset dpms force off`, the internal display does not turn off. *sigh*

Probably relatedly, and likely showing there is something more wrong, disabling the display (with xrandr) does not turn it off either.

### CODE REVIEW

**Comment by samueldr** [comment]
(From the Matrix room)

* * *

@zhaofengli asked:

> Will try out the update in a bit. Does the userspace fan controller work, or is [patching the hwmon name](https://github.com/Jovian-Experiments/Jovian-NixOS/pull/48/commits/f6b8a8ef107bf5e4e935e8a58c216d3f48014666) still needed?

* * *

I wonder how vendor handles that

```
.../class/hwmon $ grep . */name
hwmon0/name:amdgpu
hwmon1/name:nvme
hwmon2/name:ACAD
hwmon3/name:BAT1
hwmon4/name:acpitz
hwmon5/name:steamdeck_hwmon
hwmon6/name:hidpp_battery_0
hwmon7/name:hidpp_battery_1
```

it seemingly might still be needed


they *are* still shipping it

```
steamdeck-images.steamos.cloud/steamdeck/20230208.1000/steamdeck-20230208.1000-snapshot.manifest.pacman
219:jupiter-fan-control 20221107.1-1
```

So it's not like they are now relying on defaults from the kernel or something else... or maybe they accidentally are.

* * *

```
.../channels/jovian-nixos 130 $ journalctl -b --unit jupiter-fan-control.service 
Feb 08 17:15:22 dashdingo systemd[1]: Started jupiter-fan-control.service.
Feb 08 17:15:22 dashdingo systemd[1]: jupiter-fan-control.service: Main process exited, code=exited, status=1/FAILURE
Feb 08 17:15:22 dashdingo systemd[1]: jupiter-fan-control.service: Control process exited, code=exited, status=1/FAILURE
[...]
Feb 08 17:15:24 dashdingo systemd[1]: jupiter-fan-control.service: Failed with result 'exit-code'.
Feb 08 17:15:24 dashdingo systemd[1]: jupiter-fan-control.service: Scheduled restart job, restart counter is at 5.
Feb 08 17:15:24 dashdingo systemd[1]: Stopped jupiter-fan-control.service.
Feb 08 17:15:24 dashdingo systemd[1]: jupiter-fan-control.service: Start request repeated too quickly.
Feb 08 17:15:24 dashdingo systemd[1]: jupiter-fan-control.service: Failed with result 'exit-code'.
Feb 08 17:15:24 dashdingo systemd[1]: Failed to start jupiter-fan-control.service.
```

~~This happens with and without the linked change. To be investigated.~~ Had to make it `kernelAtLeast` instead of checking strictly on `6.0`.

```
.../channels/jovian-nixos 130 $ systemctl status jupiter-fan-control.service 
● jupiter-fan-control.service
     Loaded: loaded (/etc/systemd/system/jupiter-fan-control.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-02-08 18:02:36 EST; 11s ago
```

So yes, confirmed at least within NixOS it will need a fixup. I'm curious what's up with the vendor OS though.

**Comment by samueldr** [comment]
`jupiter-fan-control` has been updated by downstream, with fixes.

 - [x] send update to the repo mirror
 - [x] update the package in this PR (dropping the workaround fix)

The end-results should be strictly equivalent, so it won't need further re-testing.

**Comment by zhaofengli** [comment]
The updated `jupiter-fan-control` works fine from my testing. We can rebase and drop the workaround commits once this is ready to be merged (after the UCM stuff).

**Comment by samueldr** [comment]
Just noting, in case this insight is useful: been running this for a while, though not really using the Steam Deck. Nothing obvious to note.

**Pull request merged**
